server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    access_log  /var/log/nginx/host.access.log  main;

    location / {
        proxy_pass http://192.168.0.123:5000;
    }
    
    location /admin {
        proxy_pass http://192.168.0.123:5001;
    }
}

