services:
  web:
    build: ./web
    ports:
      - "5000:80"

  nginx:
    image: nginx:stable-alpine3.19-perl
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx